[versions]
kotlin = "2.1.0"
guava = "33.1.0-jre"
junit = "5.10.1"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
